// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_ from "./routes/[slug].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_slug_check from "./routes/api/[slug]/check.ts";
import * as $api_auth_login from "./routes/api/auth/login.tsx";
import * as $create from "./routes/create.tsx";
import * as $easy from "./routes/easy.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $latest from "./routes/latest.tsx";
import * as $random_size_ from "./routes/random/[size].tsx";
import * as $Form from "./islands/Form.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $LoginParamsConverter from "./islands/LoginParamsConverter.tsx";
import * as $Puzzle from "./islands/Puzzle.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $_slug_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/[slug]/check.ts": $api_slug_check,
    "./routes/api/auth/login.tsx": $api_auth_login,
    "./routes/create.tsx": $create,
    "./routes/easy.tsx": $easy,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/latest.tsx": $latest,
    "./routes/random/[size].tsx": $random_size_,
  },
  islands: {
    "./islands/Form.tsx": $Form,
    "./islands/Header.tsx": $Header,
    "./islands/LoginParamsConverter.tsx": $LoginParamsConverter,
    "./islands/Puzzle.tsx": $Puzzle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
